import socket
from concurrent.futures import ThreadPoolExecutor, as_completed

from utils.output import section, info, success, warning, error, result, table

COMMON_SUBDOMAINS = [
    "www", "mail", "admin", "blog", "dev", "test", "api", "app", "cdn",
    "static", "m", "mobile", "webmail", "vpn", "remote", "secure", "portal",
    "support", "help", "shop", "store", "forum", "community", "wiki",
    "docs", "status", "monitor", "git", "jenkins", "jira", "confluence",
    "images", "img", "assets", "files", "ftp", "download", "upload",
    "backup", "db", "database", "sql", "mysql", "redis", "staging",
    "beta", "alpha", "demo", "test", "stage", "sandbox", "develop",
    "stage", "prod", "production", "local", "mail2", "mx", "ns1", "ns2",
    "ns3", "dns", "dns1", "dns2", "smtp", "pop3", "imap", "autodiscover",
    "owa", "exchange", "lync", "sip", "chat", "cloud", "service",
    "services", "api2", "api3", "ws", "websocket", "www2", "www3",
    "web", "cms", "wp", "wordpress", "joomla", "drupal", "phpmyadmin",
    "phpadmin", "myadmin", "adminer", "administrator", "login", "signin",
    "auth", "sso", "oauth", "idp", "saml", "analytics", "tracking",
    "metrics", "logs", "report", "reports", "dashboard", "console",
    "manager", "management", "config", "configuration", "setup",
    "install", "update", "upgrade", "mon", "nagios", "zabbix",
    "graphite", "grafana", "kibana", "elastic", "logstash",
    "puppet", "chef", "ansible", "salt", "k8s", "kubernetes",
    "docker", "registry", "nexus", "artifactory", "sonar", "sonarqube",
    "jenkins", "travis", "circleci", "teamcity", "build", "ci",
    "new", "old", "v2", "v3", "v1", "latest", "current", "archive",
    "labs", "playground", "sandbox", "demo", "test", "testing",
    "stage", "staging", "dev", "develop", "development",
    "prod", "production", "live", "release", "master", "main",
    "swagger", "redoc", "api-docs", "docs-api", "api-documentation",
    "newsletter", "mailing", "billing", "invoice", "payment",
    "checkout", "cart", "shop", "store", "market", "marketplace",
    "recruit", "careers", "jobs", "hr", "employee", "staff",
    "partners", "partner", "vendor", "vendors", "supplier",
    "wholesale", "distributor", "reseller",
    "a", "acct", "adfs", "ads", "adserver", "affiliate", "agent", "agile",
    "ajax", "alert", "analytics", "android", "announce", "anon", "answer",
    "answers", "apache", "api-internal", "api-private", "api-public", "api-staging",
    "app-admin", "app-api", "app-dev", "app-staging", "app-test", "apps",
    "archive", "archives", "article", "articles", "ask", "atlas", "audit",
    "auditor", "auth-api", "auth-dev", "auth-staging", "auth-test",
    "authentication", "author", "authorization", "authors", "automation",
    "avatar", "avatars", "aws", "azure", "b2b", "backup", "backups",
    "bandwidth", "bank", "base", "bash", "basic", "basket", "bastion",
    "batch", "beacon", "beanstalk", "beats", "berlin", "billing", "binary",
    "blackhole", "blob", "block", "blocked", "blogger", "blogs", "board",
    "boards", "bolt", "book", "booking", "books", "bootstrap", "bot", "bots",
    "bounce", "box", "broadcast", "broadcasts", "broker", "bucket", "buddy",
    "bug", "bugzilla", "build", "builder", "builders", "building", "builds",
    "bulletin", "bundle", "bundles", "bus", "business", "buy", "cable",
    "cache", "cached", "calendar", "call", "calls", "cam", "camera",
    "campaign", "campaigns", "campus", "cancel", "captcha", "capture",
    "card", "cards", "career", "careers", "cargo", "cart", "carts",
    "cas", "case", "cases", "cash", "catalog", "catalogs", "catalogue",
    "catch", "category", "cc", "cd", "cds", "cell", "census", "center",
    "centers", "central", "cert", "certificate", "certificates",
    "chain", "challenge", "champion", "channel", "channels", "chaos",
    "chapter", "charge", "charges", "charity", "chart", "charter", "charts",
    "chat", "check", "checker", "checkin", "checkout", "checks",
    "chef", "chicago", "china", "chrome", "ci", "cinema",
    "circle", "circles", "cisco", "citizen", "city", "claim", "claims",
    "clark", "class", "classes", "classic", "classroom", "clean",
    "click", "client", "clients", "clinic", "clinical", "clinics",
    "clock", "clone", "close", "closed", "cloud", "cloudapp", "cloudfront",
    "clouds", "club", "clubs", "cluster", "clusters", "cm", "cms",
    "coach", "coaching", "code", "coder", "coders", "codes", "coding",
    "coffee", "cold", "collab", "collaboration", "collapse", "colleague",
    "collect", "collection", "collections", "collector", "college",
    "color", "colorado", "column", "columns", "combat", "combo",
    "comics", "command", "commander", "commands", "comment", "comments",
    "commerce", "commercial", "commit", "committee", "commodity",
    "common", "commons", "communication", "communications", "community",
    "company", "compare", "comparison", "compass", "compatible",
    "competition", "competitive", "competitor", "complaint", "complaints",
    "complete", "compliance", "component", "components",
    "composer", "composite", "computer", "computers", "computing",
    "concept", "concepts", "concern", "concerns", "concert", "concerts",
    "condition", "conditions", "conference", "conferences",
    "confidential", "config", "configuration", "configure",
    "connect", "connected", "connection", "connections", "connector",
    "consensus", "consent", "conservative", "console",
    "consolidate", "consortium", "constant", "constants",
    "constraint", "constraints", "construct", "construction",
    "consult", "consultant", "consulting", "consumer", "consumers",
    "contact", "contacts", "container", "containers", "content", "contents",
    "contest", "contests", "context", "continent", "continental",
    "continue", "contract", "contractor", "contracts", "control",
    "controller", "controllers", "controls", "convention",
    "conversion", "convert", "converter", "cook", "cookbook",
    "cookie", "cookies", "cooking", "cool", "cooper",
    "cooperation", "coordinate", "coordination", "coordinator",
    "cope", "copies", "copy", "core", "corner", "corporate",
    "corporation", "corps", "correct", "correction", "corrections",
    "cost", "costs", "couch", "council", "counsel", "counselor",
    "count", "counter", "counters", "countries", "country",
    "county", "coupon", "coupons", "courier", "course", "courses",
    "court", "courts", "cover", "coverage", "covered", "covers",
    "cpanel", "crack", "cracked", "craft", "crash",
    "crawl", "crawler", "crawlers", "crazy", "cream",
    "create", "created", "creation", "creations", "creative",
    "creator", "creators", "credit", "credits", "crew",
    "crime", "crimes", "criminal", "crisis", "criteria",
    "critical", "crm", "cron", "crop", "crops",
    "cross", "crossing", "crowd", "crowded", "crowdfunding",
    "crown", "crunch", "crystal", "cto", "cube", "culture", "cultures",
    "cup", "curriculum", "cursor", "custody", "custom", "customer",
    "customers", "customs", "cut", "cuts", "cutting",
    "cyber", "cycle", "cycles", "cycling", "daemon",
    "daily", "dairy", "dallas", "damage", "dance", "dancing",
    "danger", "dark", "darkness", "dash", "dashboard", "data",
    "database", "databases", "datacenter", "datastore",
    "date", "dates", "dawn", "day", "days", "db", "dba",
    "dead", "deadline", "deal", "dealer", "dealers", "dealing", "deals",
    "dear", "death", "debate", "debug", "debugger",
    "decide", "decision", "decisions", "deck", "declaration",
    "declare", "decline", "decor", "decoration", "decrease",
    "dedicated", "dedication", "deed", "deep", "deer",
    "default", "defaults", "defeat", "defect", "defects",
    "defend", "defendant", "defense", "defenses", "defensive",
    "deficit", "define", "defined", "definition", "definitions",
    "degree", "degrees", "delay", "delays", "delete", "deleted",
    "deletion", "delhi", "deliver", "delivered", "delivery",
    "delta", "demand", "demands", "demo", "democracy", "democrat",
    "democratic", "demolition", "demonstrate", "demonstration",
    "denial", "denied", "denmark", "dennis", "density",
    "dental", "dentist", "dentists", "denver", "department",
    "departments", "departure", "depend", "dependent", "deploy",
    "deployed", "deploying", "deployment", "deposit", "deposits",
    "depot", "depress", "depression", "depth", "deputy",
    "derby", "derive", "des", "desert", "deserve", "design",
    "designated", "designation", "designed", "designer", "designers",
    "designing", "designs", "desire", "desk", "desktop", "desktops",
    "desperate", "despite", "destination", "destiny",
    "destroy", "destruction", "detach", "detail", "details",
    "detect", "detected", "detection", "detective", "detector",
    "detention", "determine", "detroit", "deutsch", "deutsche",
    "deutschland", "dev-api", "dev-app", "dev-db", "dev-www",
    "dev2", "dev3", "developer", "developers", "development",
    "devices", "devops", "digital", "dinner", "direct",
    "direction", "directions", "directive", "director", "directors",
    "directory", "dirty", "disabled", "disaster", "discharge",
    "discipline", "disciplines", "disclose", "disclosure",
    "discount", "discounts", "discover", "discovery", "discretion",
    "discrimination", "discuss", "discussed", "discusses",
    "discussing", "discussion", "discussions", "disease",
    "diseases", "dish", "dishes", "disk", "disks",
    "dismiss", "dismissal", "disney", "disorder", "dispatch",
    "display", "displays", "disposal", "dispose", "dispute",
    "disputes", "distance", "distances", "distant", "distinct",
    "distinction", "distinctive", "distinguish", "distribute",
    "distributed", "distribution", "distributions", "distributor",
    "distributors", "district", "districts", "disturb",
    "disturbance", "dive", "diverse", "diversity", "divide",
    "divided", "dividend", "divine", "diving", "division",
    "divisions", "divorce", "diy", "dj", "dna",
    "do", "doc", "dock", "doctor", "doctors", "doctrine",
    "document", "documentary", "documentation", "documented",
    "documents", "dodge", "dog", "dogs", "doing", "doll",
    "dollar", "dollars", "domain", "domains", "dome", "domestic",
    "dominant", "dominate", "domination", "dominican",
    "don", "donate", "donated", "donation", "donations",
    "done", "donor", "donors", "door", "doors", "dose",
    "dot", "double", "doubt", "doug", "dough", "douglas",
    "dow", "down", "downloading", "downloads",
    "downtown", "dozen", "dozens", "draft", "drafts",
    "drag", "dragon", "drain", "drainage", "dramatic",
    "dramatically", "drank", "drapes", "drastic", "draw",
    "drawing", "drawings", "drawn", "draws", "dream",
    "dreams", "dress", "dressed", "dresser", "dresses",
    "dressing", "drew", "dried", "drift", "drill",
    "drilling", "drills", "drink", "drinking", "drinks",
    "drive", "driven", "driver", "drivers", "drives",
    "driveway", "driving", "drop", "dropped", "dropping",
    "drops", "drought", "drove", "drug", "drugs", "drum",
    "drums", "drunk", "dry", "dub", "dublin", "duchess",
    "duck", "ducks", "due", "duke", "dull", "duly",
    "dumb", "dump", "dumped", "dumping", "duncan", "dune",
    "dunes", "dungeon", "duplex", "duplicate", "durability",
    "durable", "duration", "durham", "during", "dust",
    "dusty", "dutch", "duties", "duty", "dvd", "dwarf",
    "dwell", "dwelling", "dying", "dynamic", "dynamics",
    "dynamite", "e", "eagle", "eagles", "ear",
    "earl", "earlier", "earliest", "early", "earn",
    "earned", "earning", "earnings", "ears", "earth",
    "earthquake", "ease", "easier", "easily", "east",
    "eastern", "easy", "eat", "eaten", "eating",
    "eats", "ebay", "ebony", "echo", "eclipse",
    "eco", "ecological", "ecology", "ecom", "ecommerce",
    "economic", "economical", "economics", "economies",
    "economy", "ecosystem", "ed", "eddie", "eden",
    "edge", "edges", "edit", "edition", "editions",
    "editor", "editorial", "editors", "educate",
    "educated", "education", "educational", "educator",
    "educators", "edward", "edwards", "eel", "effect",
    "effective", "effectively", "effectiveness",
    "effects", "efficiency", "efficient", "efficiently",
    "effort", "efforts", "egg", "eggs", "ego",
    "egypt", "egyptian", "eight", "eighth", "eighty",
    "either", "el", "elaborate", "elbow", "elder",
    "elderly", "elders", "elect", "elected", "election",
    "elections", "electoral", "electric", "electrical",
    "electricity", "electro", "electron", "electronic",
    "electronics", "elegance", "elegant", "element",
    "elements", "elephant", "elevated", "elevation",
    "elevator", "eleven", "eligible", "eliminate",
    "elimination", "elite", "else", "elsewhere",
    "email", "email2", "emails", "embassy", "embedded",
    "embrace", "emerge", "emergency", "emerging",
    "emission", "emissions", "emma", "emotion",
    "emotional", "emotions", "emperor", "emphasis",
    "empire", "empirical", "employ", "employee",
    "employees", "employer", "employers", "employment",
    "empower", "empty", "ems", "enable", "enabled",
    "enables", "enabling", "encode", "encoder",
    "encoding", "encounter", "encourage", "encryption",
    "end", "endangered", "ended", "endless", "endorse",
    "endorsement", "endpoint", "endpoints", "ends",
    "enemy", "energy", "enforce", "enforced",
    "enforcement", "engage", "engaged", "engagement",
    "engine", "engineer", "engineering", "engineers",
    "engines", "england", "english", "enhance",
    "enhanced", "enhancement", "enjoy", "enlarge",
    "enormous", "enough", "enrich", "enroll",
    "enrollment", "ensure", "enter", "enterprise",
    "enterprises", "entertain", "entertainment",
    "enthusiast", "entire", "entitled", "entity",
    "entrance", "entrepreneur", "entries", "entry",
    "envelope", "envelopes", "environment",
    "env", "epic", "epidemic", "episode", "episodes",
    "equal", "equality", "equally", "equation",
    "equilibrium", "equipment", "equity", "equivalent",
    "era", "eric", "erosion", "error", "errors",
    "escape", "escort", "espresso", "essay", "essays",
    "essence", "essential", "essentials", "establish",
    "estate", "estates", "estimate", "estimates",
    "estimation", "eternal", "ethical", "ethics",
    "ethnic", "europe", "european", "eva", "evacuate",
    "evaluate", "evaluation", "evan", "evangelical",
    "eve", "even", "evening", "event", "events",
    "eventual", "eventually", "ever", "everest",
    "every", "everybody", "everyday", "everyone",
    "everything", "everywhere", "evil", "evolve",
    "evolved", "evolving", "ex", "exact", "exactly",
    "exam", "examination", "examine", "example",
    "examples", "exams", "exceed", "excel",
    "excellence", "excellent", "except", "exception",
    "exceptions", "excerpt", "excess", "excessive",
    "exchange", "exchanges", "excite", "excited",
    "excitement", "exciting", "exclude", "exclusion",
    "exclusive", "exclusively", "excuse", "exec",
    "execute", "executed", "execution", "executive",
    "executives", "executor", "exempt", "exemption",
    "exercise", "exhaust", "exhausted", "exhibit",
    "exhibition", "exhibits", "exile", "exist",
    "existed", "existence", "existing", "exists",
    "exit", "exits", "exotic", "expand", "expanded",
    "expanding", "expansion", "expect", "expectation",
    "expectations", "expected", "expedition",
    "expense", "expenses", "expensive", "experience",
    "experiences", "experiment", "experimental",
    "experiments", "expert", "expertise", "experts",
    "expiration", "expire", "expired", "expires",
    "explain", "explanation", "explicit", "explode",
    "exploit", "exploitation", "exploration",
    "explore", "explored", "explorer", "explosion",
    "explosive", "export", "exports", "expose",
    "exposed", "exposes", "exposure", "express",
    "expressed", "expression", "expressions",
    "extend", "extended", "extending", "extends",
    "extension", "extensions", "extensive", "extent",
    "exterior", "external", "extra", "extract",
    "extraction", "extraordinary", "extreme",
    "extremely", "eye", "eyebrow", "eyes",
    "fabric", "fabulous", "face", "faced", "facet",
    "facial", "facilitate", "facilities", "facility",
    "facing", "fact", "factor", "factory", "facts",
    "faculty", "fade", "fail", "failed", "failing",
    "fails", "failure", "failures", "faint", "fair",
    "fairly", "fairness", "faith", "fake", "fall",
    "fallen", "falling", "falls", "false", "fame",
    "familiar", "family", "famous", "fan", "fancy",
    "fans", "fantastic", "fantasy", "faq", "faqs",
    "far", "fare", "farewell", "farm", "farmer",
    "farmers", "farming", "farms", "fascinating",
    "fashion", "fast", "fasten", "faster", "fat",
    "fatal", "fate", "father", "fathers", "fatigue",
    "fault", "faults", "favor", "favorite",
    "favorites", "favors", "favourite", "favourites",
    "fear", "fears", "feasible", "feast", "feat",
    "feature", "features", "federal", "federation",
    "fee", "feed", "feedback", "feeder", "feeding",
    "feeds", "feel", "feeling", "feelings", "fees",
    "feet", "fellow", "fellows", "fellowship",
    "female", "females", "fence", "ferrari",
    "ferry", "fertile", "festival", "festivals",
    "fetch", "fever", "fiber", "fibre", "fiction",
    "field", "fields", "fierce", "fifteen", "fifth",
    "fifty", "fig", "fight", "fighter", "fighting",
    "figure", "figures", "file", "filed", "files",
    "filing", "fill", "filled", "filling", "film",
    "films", "filter", "filtering", "filters",
    "fin", "final", "finale", "finalist", "finally",
    "finance", "finances", "financial", "financing",
    "find", "finder", "finding", "findings", "fine",
    "finest", "finger", "fingers", "finish",
    "finished", "finishing", "finite", "finland",
    "finnish", "fire", "fireball", "firebird",
    "firefox", "fireman", "firewall", "firewalls",
    "firewire", "firm", "firmly", "firms",
    "firmware", "first", "fiscal", "fish",
    "fisher", "fisheries", "fishes", "fishing",
    "fit", "fitness", "fits", "fitted", "fitting",
    "five", "fix", "fixed", "fixes", "fixtures",
    "flag", "flags", "flame", "flames", "flash",
    "flashing", "flat", "flavor", "flavors",
    "flavour", "flavours", "fleet", "flesh",
    "flex", "flexibility", "flexible", "flickr",
    "flight", "flights", "flip", "float",
    "floating", "flock", "flood", "floor", "floors",
    "floppy", "floral", "florence", "florida",
    "florist", "flow", "flower", "flowers",
    "flows", "fluid", "fluids", "flush", "fly",
    "flyer", "flying", "foam", "focal", "focus",
    "focused", "focuses", "fog", "fold", "folder",
    "folders", "folding", "folk", "folks", "follow",
    "follower", "followers", "following", "follows",
    "food", "foods", "foot", "footage", "football",
    "footnote", "footprint", "footprints",
    "force", "forced", "forces", "ford", "forecast",
    "forecasts", "foreign", "forest", "forests",
    "forever", "forge", "forget", "forgive",
    "fork", "forks", "form", "formal", "format",
    "formation", "formations", "formats", "formed",
    "former", "forming", "forms", "formula",
    "formulas", "fort", "forth", "fortune",
    "forty", "forum", "forums", "forward",
    "forwarded", "forwards", "fossil", "foster",
    "found", "foundation", "foundations",
    "founded", "founder", "founders", "founding",
    "fountain", "four", "fourth", "fox",
    "fraction", "fragile", "fragment", "fragments",
    "frame", "framed", "frames", "framework",
    "frameworks", "france", "franchise",
    "franchises", "frank", "frankfurt", "franklin",
    "fraud", "fred", "frederick", "free",
    "freedom", "freelance", "freelancer", "freely",
    "freight", "french", "frequency", "frequent",
    "fresh", "friday", "fridge", "friend",
    "friendly", "friends", "friendship", "frog",
    "front", "frontend", "frontier", "frontpage",
    "frost", "frozen", "fruit", "fruits",
    "fuel", "full", "fully", "fun",
    "function", "functional", "functionality",
    "functions", "fund", "fundamental", "funding",
    "funds", "funeral", "funny", "fur",
    "furniture", "further", "fusion", "future",
    "futures", "gadget", "gadgets", "gain",
    "gained", "gaining", "gains", "galaxy",
    "gallery", "galleries", "gamble", "gambling",
    "game", "gamepad", "games", "gaming",
    "gang", "gap", "garage", "garbage", "garden",
    "gardening", "gardens", "garlic", "gas",
    "gate", "gates", "gateway", "gateways",
    "gather", "gathered", "gathering", "gauge",
    "gay", "gaze", "gear", "geek", "geeks",
    "gender", "gene", "general", "generally",
    "generate", "generated", "generates",
    "generating", "generation", "generations",
    "generator", "generators", "generic",
    "generous", "genes", "genesis", "genetic",
    "genetics", "geneva", "genius", "genre",
    "genres", "gentle", "gentleman", "gentlemen",
    "genuine", "geo", "geographic", "geography",
    "geology", "george", "georgia", "german",
    "germany", "gesture", "get", "gets", "getting",
    "ghost", "ghosts", "giant", "giants",
    "gift", "gifts", "gig", "gilbert",
    "ginger", "girl", "girlfriend", "girls",
    "give", "given", "gives", "giving",
    "glad", "glance", "glass", "glasses",
    "glen", "glenn", "global", "globe",
    "glory", "glossary", "glove", "gloves",
    "glucose", "glue", "goal", "goals",
    "god", "gods", "goes", "gold", "golden",
    "golf", "gone", "good", "goodbye",
    "goodness", "goods", "google", "gordon",
    "gore", "gospel", "gossip", "govern",
    "governance", "governing", "government",
    "governments", "governor", "grab", "grace",
    "grade", "grades", "graduate", "graduated",
    "graduates", "graduation", "grain",
    "grains", "gram", "grammar", "grand",
    "grande", "grandfather", "grandma",
    "grandmother", "grandparents", "granite",
    "grant", "grants", "grape", "grapes",
    "graph", "graphic", "graphical", "graphics",
    "graphite", "graphs", "grasp", "grass",
    "grateful", "grave", "gravel", "gravity",
    "gray", "great", "greater", "greatest",
    "greece", "greek", "green", "greens",
    "greet", "greeting", "greetings",
    "grey", "grid", "grief", "grill",
    "grind", "grip", "grocery", "groove",
    "gross", "ground", "grounds", "group",
    "groups", "grove", "grow", "growing",
    "grown", "growth", "guarantee",
    "guarantees", "guard", "guardian",
    "guardians", "guards", "guess", "guest",
    "guests", "guidance", "guide", "guided",
    "guidelines", "guides", "guild",
    "guilty", "guitar", "guitars",
    "gun", "guns", "guru", "guy",
    "guys", "gym", "gymnastics",
    "habit", "habitat", "habits", "hack",
    "hacker", "hackers", "hacking",
    "hair", "half", "hall", "halls",
    "halt", "hamburg", "hamburger", "hammer",
    "hand", "handbook", "handed", "handheld",
    "handle", "handler", "handlers", "handles",
    "handling", "hands", "handshake", "handy",
    "hang", "hanger", "hanging", "hangout",
    "happen", "happened", "happening",
    "happens", "happiness", "happy",
    "harbor", "harbour", "hard", "hardcover",
    "hardcore", "harden", "hardening",
    "hardly", "hardness", "hardship",
    "hardware", "harm", "harmful", "harmony",
    "harold", "harper", "harris", "harry",
    "harsh", "harvard", "harvest",
    "hash", "hashtag", "hate", "haul",
    "haunt", "haunted", "have", "having",
    "hawaii", "hawk", "hawks", "hay",
    "hazard", "hazards", "hd",
    "head", "headache", "header", "headers",
    "heading", "headline", "headlines",
    "headphone", "headphones",
    "headquarters", "heads", "headset",
    "heal", "health", "healthcare", "healthy",
    "hear", "heard", "hearing", "heart",
    "hearts", "heat", "heated", "heater",
    "heating", "heaven", "heavily", "heavy",
    "height", "heights", "held",
    "helicopter", "hell", "hello", "helm",
    "helmet", "help", "helper", "helpers",
    "helpful", "helping", "helps",
    "hen", "henry", "herald", "herb",
    "herbal", "herbs", "herd", "here",
    "heritage", "hero", "heroes", "heroic",
    "hidden", "hide", "hierarchy",
    "high", "highland", "highlight",
    "highlights", "highly", "highway",
    "highways", "hike", "hiking", "hill",
    "hills", "hint", "hints", "hip",
    "hire", "hired", "hiring",
    "historic", "historical", "history",
    "hit", "hits", "hitting",
    "hobby", "hockey", "hold", "holder",
    "holders", "holding", "holdings",
    "holds", "hole", "holes", "holiday",
    "holidays", "holland", "hollow",
    "hollywood", "holy", "home", "homepage",
    "homes", "hometown", "homework",
    "honest", "honesty", "honey",
    "honor", "honors", "honour",
    "hook", "hooks", "hope", "hoped",
    "hopes", "hoping", "horizon",
    "horizontal", "horn", "horrible",
    "horror", "horse", "horses",
    "hospital", "hospitals", "host",
    "hosted", "hostel", "hostels",
    "hostile", "hosting", "hosts",
    "hot", "hotel", "hotels", "hotline",
    "hour", "hourly", "hours", "house",
    "household", "houses", "housing",
    "houston", "how", "however", "howto",
    "hub", "huge", "human", "humanitarian",
    "humanity", "humans", "humble",
    "humidity", "humor", "humour",
    "hundred", "hundreds", "hung",
    "hungarian", "hungary", "hunger",
    "hungry", "hunt", "hunter", "hunters",
    "hunting", "hurricane", "hurry",
    "hurt", "husband", "hut",
    "hybrid", "hybrids", "hydrogen",
    "hygiene", "hype", "hypothesis",
]


def resolve_subdomain(domain, subdomain, timeout=5):
    hostname = f"{subdomain}.{domain}"
    try:
        ip = socket.gethostbyname(hostname)
        try:
            host = socket.gethostbyaddr(ip)
            ptr = host[0]
        except:
            ptr = ""
        return subdomain, ip, ptr
    except socket.gaierror:
        return None


class SubdomainFinder:
    name = "subdomain"
    description = "Discover subdomains of a target domain"

    @staticmethod
    def run(target, wordlist=None, threads=50):
        if target.startswith(("http://", "https://")):
            from urllib.parse import urlparse
            target = urlparse(target).netloc or target
        section(f"Subdomain Finder: {target}")

        subdomains = COMMON_SUBDOMAINS.copy()
        if wordlist:
            try:
                with open(wordlist) as f:
                    extra = [line.strip() for line in f if line.strip()]
                    subdomains.extend(extra)
                info(f"Loaded {len(extra)} additional subdomains from {wordlist}")
            except FileNotFoundError:
                error(f"Wordlist not found: {wordlist}")

        info(f"Checking {len(subdomains)} subdomains of {target}...")

        found = []
        with ThreadPoolExecutor(max_workers=threads) as executor:
            futures = {executor.submit(resolve_subdomain, target, sd): sd for sd in subdomains}
            for i, future in enumerate(as_completed(futures)):
                result_data = future.result()
                if result_data:
                    sub, ip, ptr = result_data
                    found.append((sub, ip, ptr))
                    success(f"{sub}.{target} -> {ip}")

        if found:
            success(f"Found {len(found)} subdomain(s):")
            table(
                ["SUBDOMAIN", "IP ADDRESS", "PTR RECORD"],
                [(f"{sd}.{target}", ip, ptr if ptr else "-") for sd, ip, ptr in found]
            )
        else:
            warning("No subdomains discovered")

        return {"target": target, "subdomains": found}
