import requests
from utils.output import section, info, success, warning, error, result, table
from utils.external_tools import wafw00f_detect

WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "headers": {"Server": "cloudflare", "CF-RAY": ".*"},
        "cookies": ["__cfduid", "__cf_bm"],
        "response": ["Attention Required!|Cloudflare", "cf-error-page"],
        "block_code": [403, 503],
    },
    {
        "name": "AWS WAF (CloudFront)",
        "headers": {"X-Cache": "Error from CloudFront", "Server": "CloudFront"},
        "cookies": [],
        "response": ["Request blocked", "waf-", "security violation"],
        "block_code": [403, 502],
    },
    {
        "name": "ModSecurity",
        "headers": {},
        "cookies": [],
        "response": ["ModSecurity", "Not Acceptable", "This error was generated by Mod_Security"],
        "block_code": [406, 403, 500],
    },
    {
        "name": "Akamai",
        "headers": {"X-Cnection": "close"},
        "cookies": ["ak_bmsc", "bm_sz", "_abck"],
        "response": ["reference number", "akamai", "blocked"],
        "block_code": [403],
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": {"X-ASM": ".*", "X-WA-Info": ".*"},
        "cookies": ["ASM", "LastMRH_Session", "MRHSession"],
        "response": ["The requested URL was rejected", "Support ID", "F5 Networks"],
        "block_code": [403, 200],
    },
    {
        "name": "Sucuri",
        "headers": {"X-Sucuri-ID": ".*", "X-Sucuri-Cache": ".*"},
        "cookies": ["sucuri_cloudproxy"],
        "response": ["Sucuri WebSite Firewall", "cloudproxy"],
        "block_code": [403],
    },
    {
        "name": "Barracuda",
        "headers": {},
        "cookies": ["barra_counter_session"],
        "response": ["Barracuda", "blocked by Barracuda"],
        "block_code": [403],
    },
    {
        "name": "Imperva (Incapsula)",
        "headers": {"X-Iinfo": ".*", "X-CDN": "Imperva"},
        "cookies": ["incap_ses_", "visid_incap_"],
        "response": ["incapsula", "_Incapsula_Resource"],
        "block_code": [403, 509],
    },
    {
        "name": "StackPath",
        "headers": {},
        "cookies": [],
        "response": ["StackPath", "stackpath"],
        "block_code": [403],
    },
    {
        "name": "Comodo cWatch",
        "headers": {},
        "cookies": ["comodo"],
        "response": ["cWatch", "Comodo"],
        "block_code": [403],
    },
    {
        "name": "Wordfence",
        "headers": {},
        "cookies": ["wfvt_"],
        "response": ["Wordfence", "Generated by Wordfence"],
        "block_code": [403, 503],
    },
    {
        "name": "Radware",
        "headers": {"X-SL-CompState": ".*"},
        "cookies": ["_aap", "radware"],
        "response": ["Radware", "Captcha"],
        "block_code": [403],
    },
    {
        "name": "FortiWeb",
        "headers": {},
        "cookies": ["FORTIWAFSID"],
        "response": ["FortiWeb", "fgd_icon"],
        "block_code": [403, 503],
    },
    {
        "name": "SafeDog",
        "headers": {"X-Powered-By": "WAF"},
        "cookies": [],
        "response": ["SafeDog", "safedog"],
        "block_code": [403],
    },
    {
        "name": "Kona (Akamai)",
        "headers": {"X-Akamai-Transformed": ".*"},
        "cookies": [],
        "response": ["AkamaiGHost"],
        "block_code": [403],
    },
    {
        "name": "LiteSpeed",
        "headers": {"Server": "LiteSpeed"},
        "cookies": [],
        "response": [],
        "block_code": [],
    },
    {
        "name": "Varnish",
        "headers": {"Via": ".*varnish", "X-Varnish": ".*"},
        "cookies": [],
        "response": [],
        "block_code": [],
    },
    {
        "name": "Naxsi",
        "headers": {},
        "cookies": [],
        "response": ["naxsi", "NAXSI"],
        "block_code": [403],
    },
    {
        "name": "WebKnight",
        "headers": {},
        "cookies": [],
        "response": ["WebKnight", "AQTRONIX"],
        "block_code": [403, 404, 500],
    },
    {
        "name": "Armor Defense",
        "headers": {},
        "cookies": ["armor"],
        "response": ["Armor"],
        "block_code": [403],
    },
    {
        "name": "Reblaze",
        "headers": {},
        "cookies": ["reblaze"],
        "response": ["Reblaze Secure"],
        "block_code": [403],
    },
    {
        "name": "PT Application Firewall",
        "headers": {"X-PT-ION": ".*"},
        "cookies": [],
        "response": ["PT Application Firewall", "ptsecurity"],
        "block_code": [403, 406],
    },
    {
        "name": "BlockDoS",
        "headers": {},
        "cookies": [],
        "response": ["BlockDoS"],
        "block_code": [403],
    },
    {
        "name": "Sitelock",
        "headers": {},
        "cookies": ["site_lock"],
        "response": ["SiteLock", "site_lock"],
        "block_code": [403],
    },
    {
        "name": "AppWall (Radware)",
        "headers": {},
        "cookies": ["radware"],
        "response": ["AppWall"],
        "block_code": [403],
    },
    {
        "name": "CrawlProtect",
        "headers": {},
        "cookies": [],
        "response": ["crawlprotect"],
        "block_code": [403, 503],
    },
    {
        "name": "Aliyun WAF",
        "headers": {"X-Cache": "error from aliyun"},
        "cookies": [],
        "response": ["Aliyun", "yundun"],
        "block_code": [403],
    },
    {
        "name": "GCP Cloud Armor",
        "headers": {"Via": ".*google.*cloud.*armor"},
        "cookies": [],
        "response": ["Google Cloud Armor"],
        "block_code": [403, 502],
    },
    {
        "name": "Azure WAF",
        "headers": {"X-Azure-Ref": ".*"},
        "cookies": [],
        "response": ["Azure Web Application Firewall", "Request blocked by"],
        "block_code": [403],
    },
]


def probe_waf(url, timeout=10):
    malicious_payloads = [
        "/?id=1' OR '1'='1",
        "/?id=<script>alert(1)</script>",
        "/.env",
        "/../../../etc/passwd",
        "/?id=1 UNION SELECT * FROM users",
    ]

    normal_resp = None
    try:
        normal_resp = requests.get(
            url, timeout=timeout,
            headers={"User-Agent": "Mozilla/5.0"},
            allow_redirects=True,
        )
    except:
        pass

    if normal_resp is None:
        return None, None

    probes = []
    for payload in malicious_payloads:
        try:
            test_url = url.rstrip("/") + payload
            resp = requests.get(
                test_url, timeout=timeout,
                headers={"User-Agent": "Mozilla/5.0"},
                allow_redirects=True,
            )
            probes.append(resp)
        except:
            pass

    return normal_resp, probes


class WAFDetector:
    name = "waf"
    description = "Detect Web Application Firewalls and reverse proxies"

    @staticmethod
    def run(target, ext=False):
        section(f"WAF Detection: {target}")

        if not target.startswith(("http://", "https://")):
            target = f"https://{target}"

        if ext:
            section("External WAF Detection (wafw00f)")
            wafw00f_results = wafw00f_detect(target)
            if wafw00f_results:
                success(f"wafw00f detected {len(wafw00f_results)} WAF(s):")
                for name, details in wafw00f_results:
                    result(name, details)
                return {"target": target, "waf": wafw00f_results}
            else:
                warning("wafw00f not available or returned no results")
            info("Falling back to built-in WAF detector...")

        normal_resp, probes = probe_waf(target)
        if normal_resp is None:
            error(f"Cannot reach {target}")
            return {"target": target, "error": "Unreachable"}

        info(f"Baseline: HTTP {normal_resp.status_code} from {target}")
        info(f"Probing with {len(probes)} malicious payloads...")

        detected = []
        normal_headers = dict(normal_resp.headers)
        normal_cookies = {c.name for c in normal_resp.cookies}
        normal_body = normal_resp.text

        for waf in WAF_SIGNATURES:
            score = 0
            evidence = []

            for h_name, h_pattern in waf["headers"].items():
                if h_name in normal_headers:
                    import re
                    if re.search(h_pattern, normal_headers[h_name], re.I):
                        score += 2
                        evidence.append(f"header: {h_name}={normal_headers[h_name][:60]}")

            for probe in probes:
                import re
                body = probe.text.lower()
                for resp_pattern in waf["response"]:
                    if re.search(resp_pattern, body, re.I):
                        score += 3
                        evidence.append(f"blocked response pattern: {resp_pattern}")
                        break

                if probe.status_code in waf.get("block_code", []):
                    if probe.status_code != normal_resp.status_code:
                        score += 2
                        evidence.append(f"block code: HTTP {probe.status_code}")

                probe_cookies = {c.name for c in probe.cookies}
                for waf_cookie in waf["cookies"]:
                    if any(waf_cookie in c for c in probe_cookies):
                        score += 2
                        evidence.append(f"cookie: {waf_cookie}")
                        break

            detected_headers = set()
            for h_name in normal_headers:
                for waf in WAF_SIGNATURES:
                    if h_name in waf["headers"]:
                        detected_headers.add(waf["name"])

            if score >= 3:
                detected.append((waf["name"], score, evidence[:3]))

        if detected:
            detected.sort(key=lambda x: -x[1])
            section(f"Detected {len(detected)} WAF/prox(ie/ies)")
            for waf_name, score, evidence in detected:
                result(waf_name, f"confidence={score}/10")
                for e in evidence:
                    info(f"  -> {e}")
        else:
            section("No WAF Detected")
            info("The target does not appear to be behind a known WAF or reverse proxy")
            info(f"Server header: {normal_headers.get('Server', 'Not disclosed')}")

        section("Interesting Headers")
        interesting = ["Server", "X-Powered-By", "X-Generator", "Via", "X-Cache",
                       "CF-RAY", "X-Sucuri-ID", "X-Iinfo", "X-Azure-Ref",
                       "X-Cdn", "X-SL-CompState", "X-Akamai-Transformed"]
        for h in interesting:
            if h in normal_headers:
                result(h, normal_headers[h][:80])

        return {"target": target, "waf": detected}
